### ISSUE TITLE
cannot find zdk.net reference

### ISSUE THREAD

**Issue by saixin** [ZoiPer/SDK_CSharpExample#1]
build the source code , but came a error
![批注 2019-08-15 152339](https://user-images.githubusercontent.com/48272347/63079358-b5de5500-bf70-11e9-83e4-205c27237503.png)

**Comment by hisvarlar** [comment]
Waiting for dll

**Comment by rasmizam** [comment]
plz help me to run this project

**Comment by ZoiPer** [comment]
Hello,

In order to get the zdk.net dll file, you will need to contact us on zoiper.com for more information.
